export const siteConfig = {
  name: "All University Updates",
  shortName: "UniUpdates",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://alluniversity.org",
  title: "All University Updates - University Notices, Results, Admissions and Exams",
  description:
    "Latest university notices, exam dates, results, admission updates, scholarships, admit cards, board notifications and entrance exam alerts for students in Bihar, Uttar Pradesh, Haryana, Delhi and across India.",
};

export const seoKeywords = [
  "all university updates",
  "all university notification",
  "all university notices",
  "latest university notice",
  "university notification India",
  "university result India",
  "university admission notice",
  "university exam date",
  "university date sheet",
  "university time table",
  "university admit card",
  "university merit list",
  "university counselling",
  "university scholarship",
  "university syllabus",
  "university circular",
  "student notification",
  "student updates India",
  "college notice",
  "college admission update",
  "college result",
  "exam notification",
  "latest exam notification",
  "exam date 2026",
  "admit card 2026",
  "result 2026",
  "admission 2026",
  "scholarship 2026",
  "entrance exam 2026",
  "government exam notification",
  "board exam notification",
  "board result",
  "board date sheet",
  "class 10 result",
  "class 12 result",
  "10th result",
  "12th result",
  "10th date sheet",
  "12th date sheet",
  "CBSE result",
  "CBSE date sheet",
  "CBSE admit card",
  "CBSE board exam",
  "ICSE result",
  "ISC result",
  "NIOS admission",
  "NIOS result",
  "Bihar Board result",
  "BSEB result",
  "BSEB 10th result",
  "BSEB 12th result",
  "Bihar Board date sheet",
  "Bihar Board admit card",
  "UP Board result",
  "UPMSP result",
  "UP Board 10th result",
  "UP Board 12th result",
  "UP Board date sheet",
  "Haryana Board result",
  "HBSE result",
  "BSEH result",
  "Delhi university notice",
  "Delhi university admission",
  "Delhi university result",
  "Bihar university notice",
  "Bihar university result",
  "Bihar university admission",
  "UP university notice",
  "UP university result",
  "UP university admission",
  "Haryana university notice",
  "Haryana university result",
  "Haryana university admission",
  "DU admission",
  "DU result",
  "DU notice",
  "Delhi University latest notice",
  "JNU admission",
  "JNU notice",
  "Jamia admission",
  "Jamia result",
  "GGSIPU admission",
  "GGSIPU result",
  "DTU admission",
  "NSUT admission",
  "BHU admission",
  "BHU result",
  "BHU notice",
  "AMU admission",
  "AMU result",
  "Allahabad University result",
  "Lucknow University result",
  "AKTU result",
  "AKTU admit card",
  "AKTU exam date",
  "CCSU result",
  "CCSU admit card",
  "CSJMU result",
  "RMLAU result",
  "MGKVP result",
  "VBSPU result",
  "MJPRU result",
  "DDU Gorakhpur University result",
  "Magadh University result",
  "Patna University result",
  "Patliputra University result",
  "Purnea University result",
  "Purnia University result",
  "LNMU result",
  "BRABU result",
  "TMBU result",
  "VKSU result",
  "JPU result",
  "BNMU result",
  "MDU result",
  "MDU Rohtak result",
  "Kurukshetra University result",
  "KUK result",
  "Gurugram University result",
  "CDLU result",
  "GJU result",
  "DCRUST result",
  "CUET UG",
  "CUET PG",
  "CUET result",
  "CUET admit card",
  "NEET UG",
  "NEET result",
  "NEET admit card",
  "JEE Main",
  "JEE Main admit card",
  "JEE Main result",
  "UGC NET",
  "UGC NET admit card",
  "UGC NET result",
  "NTA notification",
  "NTA exam calendar",
  "NTA admit card",
  "NTA result",
  "student notice Hindi",
  "college notice Hindi",
  "university ka result",
  "university ka notice",
  "exam date kab hai",
  "admission form kab niklega",
  "result kab aayega",
  "admit card download",
  "sarkari university result",
  "latest education news India",
  "education update for students",
];
